name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 3: Inject API Key into chat.js
      - name: Inject API Key
        run: |
          sed -i "s|{{APIKEY}}|${{ secrets.APIKEY }}|g" assets/js/chat.js

      # Step 4: Verify API Key replacement (Optional for Debugging)
      - name: Verify API Key in chat.js
        run: |
          cat assets/js/chat.js

      # Step 5: Print chat.js for verification
      - name: Verify chat.js
        run: cat assets/js/chat.js

      # Step 6: Build the project
      - name: Build project
        run: |
          bundle exec jekyll build

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site