name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up environment
      - name: Setup Node.js (for managing .env file if needed)
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Inject API Key
      - name: Inject API Key
        run: |
          echo "API_KEY=${{ secrets.APIKEY }}" > .env

      # Step 5: Verify API Key presence (Optional for Debugging)
      - name: Verify API Key in .env
        run: cat .env

      # Step 6: Build the project
      - name: Build project
        run: |
          bundle exec jekyll build

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site