name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies (if needed, for example Jekyll)
      - name: Install dependencies
        run: |
          bundle install

      # Step 3: Inject API Key
      - name: Replace API Key
        run: |
          sed -i "s/{{APIKEY}}/${{ secrets.APIKEY }}/g" assets/js/chat.js

      # Step 4: Build the project (if needed)
      - name: Build project
        run: |
          bundle exec jekyll build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site