name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 3: Remove previous build artifacts (确保干净的构建环境)
      - name: Clean previous build artifacts
        run: |
          rm -rf _site assets/js/chat.js

      # Step 4: Inject API Key
      
      # - name: Inject API Key
      #   run: |
      #     sed -i "s|{{APIKEY}}|${{ secrets.APIKEY }}|g" assets/js/chat.js

      - name: Inject Secrets
        run: |
          echo "APIKEY=${{ secrets.APIKEY }}" >> _config.yml

      # Step 5: Verify API Key replacement (调试用，确保替换生效)
      - name: Verify API Key replacement
        run: |
          cat assets/js/chat.js

      # Step 6: Build the project
      - name: Build project
        run: |
          bundle exec jekyll build

      # Step 7: List built files (Optional for debugging)
      - name: List built files
        run: |
          ls -R ./_site

      # Step 8: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site