name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 3: Inject API Key
      - name: Replace API Key
        run: |
          sed -i "s|{{APIKEY}}|${{ secrets.APIKEY }}|g" assets/js/chat.js

      # Step 4: Verify API Key replacement
      - name: Verify API Key replacement
        run: |
          cat assets/js/chat.js

      # Step 5: Build the project
      - name: Build project
        run: |
          bundle exec jekyll build

      # Step 6: List built files (optional for debugging)
      - name: List built files
        run: |
          ls -R ./_site

      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site